title:              FASTSQUID's Blog
email:              dlwjdaud1@gmail.com
description:        "끄적끄적"
author:             JEONGMYUNG LEE
baseurl:            ""
url:                "https://fast-squid.github.io"
remote_theme:       StartBootstrap/startbootstrap-clean-blog-jekyll
# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
